name: movie_mixer
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  intl: ^0.18.0
  signalr_netcore: ^1.3.3
  url_launcher: ^6.1.10
  share: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0
  dio: ^5.1.1
  shared_preferences: ^2.0.15
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Clip
      fonts:
        - asset: assets/fonts/Clip.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
    - family: Lemon Tuesday
      fonts:
        - asset: assets/fonts/LemonTuesday.ttf
          weight: 400
